FROM nginx:stable-alpine
LABEL org.opencontainers.image.source="https://github.com/sachidumaleesha/turiba-devops-labs"
LABEL org.opencontainers.image.description="Lab 1 static page by Diwan Sachidu"
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80